CompanySiteApp/Models/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CompanySiteApp.Models
{
    public class Company
    {
        //Primary Key
        [Key]
        public int CompanyID { get; set; }
        [Required]
        public string CompanyName { get; set; }
    }
}

CompanySiteApp/Models/CompanySite.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CompanySiteApp.Models
{
    public class CompanySite
    {
        [ForeignKey("Company")]
        [Required]
        public int CompanyID { get; set; }
        [ForeignKey("Site")]
        [Required]
        public int SiteID { get; set; }
        [Required]
        public bool IsMainSite { get; set; }
    }
}

CompanySiteApp/Models/CompanySiteDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CompanySiteApp.Models
{
    public class CompanySiteDetails
    {
        [Required]
        public int CompanyDetailID { get; set; }
        [Required]
        public int CompanySiteID { get; set; }
        [Required]
        public int CompanyID {get;set;}
        [Required]
        public string CompanyName {get;set;}
        [Required]
        public int SiteID {get;set;}
        [Required]
        public string SiteName { get; set; }
        [Required]
        public string IsMainSite {get;set;}
        public string Notes {get;set;}
        [Required]
        public string PhoneNumber { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime StartDate { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime EndDate { get; set; }
    }
}

CompanySiteApp/Models/Result.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CompanySiteApp.Models
{
    public class Result
    {
        public int ResultID;
        public string ResultMessage;
    }
}

CompanySiteApp/Models/Site.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CompanySiteApp.Models
{
    public class Site
    {
        //Primary Key
        [Key]
        public int SiteID { get; set; }
        [Required]
        public string SiteName { get; set; }
        public string Notes { get; set; }
    }
}

CompanySiteApp/Controllers/CompanySiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CompanySiteApp.DataAccess;
using CompanySiteApp.Models;

namespace CompanySiteApp.Controllers
{
    public class CompanySiteController : Controller
    {
        // GET: CompanySite
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CompanySiteDetails()
        {
            CompanySiteDetailsDAL compSiteDetails = new CompanySiteDetailsDAL();
            return View(compSiteDetails.getCompanySiteDetails());
        }

        public ActionResult CreateCompany()
        {
            ViewBag.Error = "";
            ViewBag.Result = "";
            return View();
        }
        [HttpPost]
        public ActionResult CreateCompany(Company company)
        {
            ViewBag.Error = "";
            ViewBag.Result = "";
            if (ModelState.IsValid)
                {
                    CompanySiteDetailsDAL compSiteDetails = new CompanySiteDetailsDAL();
                    Result processMessage = compSiteDetails.addCompany(company);
                    if (processMessage.ResultID == 0)
                         ViewBag.Result = processMessage.ResultMessage;
                    else ViewBag.Error = processMessage.ResultMessage;
                }
            return View();
        }
        public ActionResult CreateSite()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateSite(Site site)
        {
            ViewBag.Error = "";
            ViewBag.Result = "";
            if (ModelState.IsValid)
            {
                CompanySiteDetailsDAL compSiteDetails = new CompanySiteDetailsDAL();
                Result processMessage = compSiteDetails.addSite(site);
                if (processMessage.ResultID == 0)
                    ViewBag.Result = processMessage.ResultMessage;
                else ViewBag.Error = processMessage.ResultMessage;
            }
            return View();
        }
        public ActionResult ViewCompanySiteDetails(CompanySiteDetails companySiteDetail)
        {
            return View();
        }
        public ActionResult EditCompanyDetails(int companyDetailID)
        {
            CompanySiteDetailsDAL compSiteDetails = new CompanySiteDetailsDAL();
            CompanySiteDetails compDetails = compSiteDetails.getCompanySiteDetailByKey(companyDetailID);
            ViewBag.IsMainSiteList = new SelectList(new List<string> { "Yes", "No" }, compDetails.IsMainSite);
            return View(compDetails);
        }
        [HttpPost]
        public ActionResult CreateCompanySiteDetails(CompanySiteDetails companySiteDetail)
        {
            ViewBag.Error = "";
            ViewBag.Result = "";
            if (ModelState.IsValid)
            {
                CompanySiteDetailsDAL compSiteDetails = new CompanySiteDetailsDAL();
                Result processMessage = compSiteDetails.addCompanySiteDetail(companySiteDetail);
                if (processMessage.ResultID == 0)
                    ViewBag.Result = processMessage.ResultMessage;
                else ViewBag.Error = processMessage.ResultMessage;
                return RedirectToAction("ViewCompanySiteDetails", companySiteDetail);
            }
            else { ViewBag.Error = "Model State is Invalid"; };
            return View();
        }
        public ActionResult CreateCompanySiteDetails()
        {
            CompanySiteDetailsDAL compSiteDetails = new CompanySiteDetailsDAL();
            ViewBag.CompanyList = new SelectList(compSiteDetails.getAllCompany(),"CompanyID","CompanyName");
            ViewBag.SiteList = new SelectList(compSiteDetails.getAllSite(), "SiteID", "SiteName");
            ViewBag.IsMainSiteList = new SelectList ( new List<string> { "Yes", "No" },"IsMainSite" );
            return View();
        }
        [HttpPost]
        public ActionResult EditCompanyDetails(CompanySiteDetails companySiteDetail)
        {
            ViewBag.Error = "";
            ViewBag.Result = "";
            if (ModelState.IsValid)
            {
                CompanySiteDetailsDAL compSiteDetails = new CompanySiteDetailsDAL();
                Result processMessage = compSiteDetails.updateCompanySiteDetail(companySiteDetail);
                if (processMessage.ResultID == 0)
                    ViewBag.Result = processMessage.ResultMessage;
                else ViewBag.Error = processMessage.ResultMessage;
                return RedirectToAction("ViewCompanySiteDetails", companySiteDetail);
            }
            else { ViewBag.Error = "Model State is Invalid"; };
            return View();
        }
    }
}

CompanySiteApp/Views/CompanySite/CompanySiteDetails.cshtml
@model IEnumerable<CompanySiteApp.Models.CompanySiteDetails>

<h1>
    Company Site Details
</h1>
<p>
    @Html.ActionLink("Create New", "CreateCompanySiteDetails","CompanySite")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SiteName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsMainSite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>

        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SiteName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsMainSite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Notes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditCompanyDetails", "CompanySite",  new{companyDetailID=item.CompanyDetailID},null) 
        </td>
    </tr>
}

</table>

CompanySiteApp/Views/CompanySite/CreateCompany.cshtml
@model CompanySiteApp.Models.Company

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    @Html.Label("", (string)ViewBag.Error, new { style = "color:#ff0000" })
    <div class="form-horizontal">
        <h4>Company</h4>
           <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    
}
@Html.Label("", (string)ViewBag.Result)
<div>
    @Html.ActionLink("Back to List", "CompanySiteDetails", "CompanySite")
</div>

CompanySiteApp/Views/CompanySite/CreateCompanySiteDetails.cshtml
@model CompanySiteApp.Models.CompanySiteDetails
@section Scripts
{
    <script src="@Url.Content("~/Scripts/CompanySite.js")"></script>
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
 
    @Html.Label("", (string)ViewBag.Error, new { style = "color:#ff0000" })

    <div class="form-horizontal">
        <h4>CompanySiteDetails</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model=>model.CompanyName, ViewBag.CompanyList as SelectList, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SiteName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SiteName, ViewBag.SiteList as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SiteName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMainSite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.IsMainSite, ViewBag.IsMainSiteList as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IsMainSite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="" type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Html.Label("", (string)ViewBag.Result)
<div>
    @Html.ActionLink("Back to List", "CompanySiteDetails","CompanySite")
</div>

CompanySiteApp/Views/CompanySite/CreateSite.cshtml
@model CompanySiteApp.Models.Site

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.Label("", (string)ViewBag.Error, new { style = "color:#ff0000" })

    <div class="form-horizontal">
        <h4>Site</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SiteName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SiteName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Html.Label("", (string)ViewBag.Result)
<div>
    @Html.ActionLink("Back to List", "CompanySiteDetails", "CompanySite")
</div>

CompanySiteApp/Views/CompanySite/EditCompanyDetails.cshtml
@model CompanySiteApp.Models.CompanySiteDetails

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Label("", (string)ViewBag.Error, new { style = "color:#ff0000" })

    <div class="form-horizontal">
        <h4>CompanySiteDetails</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.CompanySiteID)
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SiteName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMainSite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.IsMainSite, ViewBag.IsMainSiteList as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IsMainSite, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--
                <div class="form-group">
                    @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>
        -->
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control"  } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control"} })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="" type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Html.Label("", (string)ViewBag.Result)
<div>
    @Html.ActionLink("Back to List", "CompanySiteDetails", "CompanySite")
</div>

CompanySiteApp/Views/CompanySite/ViewCompanySiteDetails.cshtml
@model CompanySiteApp.Models.CompanySiteDetails

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Label("", (string)ViewBag.Error, new { style = "color:#ff0000" })

    <div class="form-horizontal">
        <h4>CompanySiteDetails</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control", @readonly ="readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SiteName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMainSite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsMainSite, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
        <!--
                <div class="form-group">
                    @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>
        -->
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
</div>
}
@Html.Label("", (string)ViewBag.Result)
<div>
    @Html.ActionLink("Back to List", "CompanySiteDetails", "CompanySite")
</div>

CompanySiteApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>Company Site Application</p>

CompanySiteApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
</address>

<address>
</address>

CompanySiteApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

CompanySiteApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Company Site Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("CompanySiteDetails", "CompanySiteDetails", "CompanySite")</li>
                    <li>@Html.ActionLink("Add Company", "CreateCompany", "CompanySite")</li>
                    <li>@Html.ActionLink("Add Site", "CreateSite", "CompanySite")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Company Site Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>